-- Generic feature controls for global and league-level overrides.
create table if not exists public.feature_controls (
  id bigint generated by default as identity primary key,
  feature_key text not null,
  scope text not null default 'global' check (scope in ('global', 'league')),
  league_id text,
  is_enabled boolean not null default true,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feature_controls_scope_league_check check (
    (scope = 'global' and league_id is null)
    or (scope = 'league' and league_id is not null)
  ),
  constraint feature_controls_unique_key_scope unique nulls not distinct (feature_key, scope, league_id)
);

comment on table public.feature_controls is
  'Controls runtime feature flags globally or per league.';
comment on column public.feature_controls.feature_key is
  'Stable key for a feature, e.g. email_notifications.';
comment on column public.feature_controls.scope is
  'global applies to all leagues; league applies to one league_id.';
comment on column public.feature_controls.league_id is
  'Target league when scope = league.';
comment on column public.feature_controls.is_enabled is
  'True to enable, false to disable.';

create or replace function public.set_updated_at_feature_controls()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_feature_controls_updated_at on public.feature_controls;
create trigger trg_feature_controls_updated_at
before update on public.feature_controls
for each row
execute procedure public.set_updated_at_feature_controls();

alter table public.feature_controls enable row level security;

-- Optional starter rows.
insert into public.feature_controls (feature_key, scope, league_id, is_enabled, description)
values
  ('email_notifications', 'global', null, true, 'Master toggle for all email notifications.'),
  ('notify_match_result_email', 'global', null, true, 'Toggle for match result notification emails specifically.')
on conflict (feature_key, scope, league_id) do nothing;
